.TH "oboinus" "1" "September, 2011" "Suniobo" "x11"
.SH "NAME"
Oboinus \- X11 background previewer and setter
.SH "SYNOPSIS"
.B oboinus
[\fIOPTION\fR]
.SH "DESCRIPTION"
In  normal  working  mode, provides an interface which help you to choose picture to be setted as background.
When  the  \-\-restore option is passed, oboinus sets background that it has a configuration for and exits immediatly,
for use in an .xinitrc/.xsession or your WM startup files.
.SH "OPTIONS"
.TP 
\fB\-h\fR, \fB\-\-help\fR
Show this help and exit
.TP 
\fB\-\-restore\fR
Restores previously saved pictures to the root displays.
.SH "SEE ALSO"
.PP 
Website: https://github.com/suniobo/oboinus
.SH "FILES"
.TP 
\fB~/.oboinus/oboinusrc\fR
Per user configuration file.
.TP 
\fB~/.oboinus/bg_image\fR
Current background image file.
.SH "AUTHOR"
Oboinus and this manual page were written by Suniobo <suniobo@fastmail.fm>.
.SH "COPYRIGHT"
Copyright (C) 2007-2012 Suniobo <suniobo@fastmail.fm>.
